name: Test Action Plugin

on:
    pull_request:
        types: [opened]
    issue_comment:
        types: [created]

jobs:
    test-pull-request-message:
        runs-on: ubuntu-latest
        outputs:
            deploy-status: ${{ steps.check.outputs.triggered }}
        steps: 
            -   uses: khan/pull-request-comment-trigger@master
                id: check
                with:
                    trigger: 'build_preview'
                    reaction: rocket
                env:
                    GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
    
    echo-variable:
        runs-on: ubuntu-latest
        needs: [test-pull-request-message]
        steps:
            - run: echo ${{ needs.test-pull-request-message.deploy-status }}                