name: Test Action Plugin

on:
    pull_request:
        types: [opened]
    issue_comment:
        types: [created]

jobs:
    build-and-push-images:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -   uses: khan/pull-request-comment-trigger@master
                id: check
                with:
                    trigger: 'build_preview'
                    reaction: rocket
                env:
                    GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

            -   run: 'echo Found it!'
                if: steps.check.outputs.triggered == 'true'