name: Test Action

on:
    push:

jobs:
    echolable:
        runs-on: ubuntu-latest
        steps: 
            -   uses: actions/checkout@v2

            -   name: Create version file
                run: |
                    ls -a
                    pwd 
                    echo "Build: ${{ github.run_number }} " >> public/version.txt
                    echo "Build time: $(date)" >> public/version.txt
                    git remote set-url origin https://github.com/Memphis0815/HelloWorld.git
                    git add .
                    git commit -m "Auto create version"
                    git fetch origin testingbranch
                    git push origin HEAD:testingbranch
    # testmessage:
    #     runs-on: ubuntu-latest
    #     outputs:
    #         status: ${{ steps.check.outputs.triggered }}
    #     steps: 
    #         -   uses: khan/pull-request-comment-trigger@master
    #             id: check
    #             with:
    #                 trigger: 'build_preview'
    #                 reaction: eyes
    #             env:
    #                 GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

    #         -   run: echo 'found it'
    #             if: steps.check.outputs.triggered == 'true'
            
    #         -   run: echo ${{ steps.check.outputs.triggered }}
    
    # echo-variable:
    #     runs-on: ubuntu-latest
    #     needs: [testmessage]
    #     steps:
    #         - run: echo ${{ needs.testmessage.outputs.status }}                