name: Test Action

on:
    push:
        branches-ignore:
            - 'staging'
            - 'master'
    label:
        types: [ created, edited ]
    
    pull_request:
        types: [ labeled, ]


jobs:
    echolable:
        runs-on: ubuntu-latest
        steps: 
            - run: echo ${{ github.event.label.name }}
            - run: echo achtion trigger on create lable

    testlabel:
        runs-on: ubuntu-latest
        if: ${{ github.event.label.name == 'build_preview' }}
        steps:
            - uses: actions/checkout@v2
            - run: echo test label work
    # testmessage:
    #     runs-on: ubuntu-latest
    #     outputs:
    #         status: ${{ steps.check.outputs.triggered }}
    #     steps: 
    #         -   uses: khan/pull-request-comment-trigger@master
    #             id: check
    #             with:
    #                 trigger: 'build_preview'
    #                 reaction: eyes
    #             env:
    #                 GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

    #         -   run: echo 'found it'
    #             if: steps.check.outputs.triggered == 'true'
            
    #         -   run: echo ${{ steps.check.outputs.triggered }}
    
    # echo-variable:
    #     runs-on: ubuntu-latest
    #     needs: [testmessage]
    #     steps:
    #         - run: echo ${{ needs.testmessage.outputs.status }}                