name: Test Action Plugin

on:
    pull_request:
        types: [opened]
    issue_comment:
        types: [created]

jobs:
    testmessage:
        runs-on: ubuntu-latest
        outputs:
            status: ${{ steps.check.outputs.triggered }}
        steps: 
            -   uses: khan/pull-request-comment-trigger@master
                id: check
                with:
                    trigger: 'build_preview'
                    reaction: eyes
                env:
                    GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

            -   run: echo 'found it'
                if: steps.check.outputs.triggered == 'true'
    
    echo-variable:
        runs-on: ubuntu-latest
        needs: [testmessage]
        steps:
            - run: echo ${{ needs.testmessage.status }}                